### ISSUE TITLE
Unable to build: `Error: Hook failed with error code 1`

### ISSUE THREAD

**Issue by manuelro** [keshavos/generator-angularjs-cordova#45]
Any ideas?

```
grunt build failed:
Error: Command failed:
Error: Hook failed with error code 1: /Users/manu/Documents/www/cordova/ServicesApp/hooks/before_build/010_grunt_build.js
    at /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/hooks/HooksRunner.js:194:23
    at _rejected (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:797:24)
    at /usr/local/lib/node_modules/cordova/node_modules/q/q.js:823:30
    at Promise.when (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:1035:31)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:741:41)
    at /usr/local/lib/node_modules/cordova/node_modules/q/q.js:557:44
    at flush (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:108:17)
    at process._tickCallback (node.js:442:13)
```

**Comment by CoreSoft2** [comment]
Same issue, any resolution?
