### ISSUE TITLE
Compilation errors when running with Node v4.1.0

### ISSUE THREAD

**Issue by jeffcharles** [keshavos/generator-angularjs-cordova#48]
When I run the generator I see output like:

```
I'm all done. Running bower install & npm install for you to install the required dependencies. If this fails, try running the command yourself.


/usr/local/Cellar/nvm/0.26.1/versions/node/v4.1.0/lib/node_modules/generator-angularjs-cordova/node_modules/wiredep/lib/detect-dependencies.js:55
  if (_.isString(componentConfigFile.main)) {
                                    ^

TypeError: Cannot read property 'main' of undefined
    at findMainFiles (/usr/local/Cellar/nvm/0.26.1/versions/node/v4.1.0/lib/node_modules/generator-angularjs-cordova/node_modules/wiredep/lib/detect-dependencies.js:55:37)
    at /usr/local/Cellar/nvm/0.26.1/versions/node/v4.1.0/lib/node_modules/generator-angularjs-cordova/node_modules/wiredep/lib/detect-dependencies.js:101:17
    at forOwn (/usr/local/Cellar/nvm/0.26.1/versions/node/v4.1.0/lib/node_modules/generator-angularjs-cordova/node_modules/wiredep/node_modules/lodash/dist/lodash.js:1301:15)
    at Function.forEach (/usr/local/Cellar/nvm/0.26.1/versions/node/v4.1.0/lib/node_modules/generator-angularjs-cordova/node_modules/wiredep/node_modules/lodash/dist/lodash.js:2595:9)
    at detect (/usr/local/Cellar/nvm/0.26.1/versions/node/v4.1.0/lib/node_modules/generator-angularjs-cordova/node_modules/wiredep/lib/detect-dependencies.js:300:5)
    at module.exports (/usr/local/Cellar/nvm/0.26.1/versions/node/v4.1.0/lib/node_modules/generator-angularjs-cordova/node_modules/wiredep/wiredep.js:39:39)
    at Generator._injectDependencies (/usr/local/Cellar/nvm/0.26.1/versions/node/v4.1.0/lib/node_modules/generator-angularjs-cordova/app/index.js:421:9)
    at /usr/local/Cellar/nvm/0.26.1/versions/node/v4.1.0/lib/node_modules/generator-angularjs-cordova/node_modules/yeoman-generator/node_modules/async/lib/async.js:232:13
    at /usr/local/Cellar/nvm/0.26.1/versions/node/v4.1.0/lib/node_modules/generator-angularjs-cordova/node_modules/yeoman-generator/node_modules/async/lib/async.js:113:21
    at /usr/local/Cellar/nvm/0.26.1/versions/node/v4.1.0/lib/node_modules/generator-angularjs-cordova/node_modules/yeoman-generator/node_modules/async/lib/async.js:24:16
```

and

```
> v8-debug@0.4.6 install /Users/jeffrey.charles/projects/iot-launch/node_modules/grunt-node-inspector/node_modules/node-inspector/node_modules/v8-debug
> node-pre-gyp install --fallback-to-build

  CXX(target) Release/obj.target/debug/src/debug.o
In file included from ../src/debug.cc:2:
../node_modules/nan/nan.h:261:25: error: redefinition of '_NanEnsureLocal'
NAN_INLINE v8::Local<T> _NanEnsureLocal(v8::Local<T> val) {
                        ^
../node_modules/nan/nan.h:256:25: note: previous definition is here
NAN_INLINE v8::Local<T> _NanEnsureLocal(v8::Handle<T> val) {
                        ^
../node_modules/nan/nan.h:661:13: error: no member named 'smalloc' in namespace 'node'
    , node::smalloc::FreeCallback callback
      ~~~~~~^
../node_modules/nan/nan.h:672:12: error: no matching function for call to 'New'
    return node::Buffer::New(v8::Isolate::GetCurrent(), data, size);
           ^~~~~~~~~~~~~~~~~
/Users/jeffrey.charles/.node-gyp/4.1.0/include/node/node_buffer.h:31:40: note: candidate function not viable: no known conversion from 'uint32_t' (aka 'unsigned int') to 'enum encoding' for 3rd argument
NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                       ^
/Users/jeffrey.charles/.node-gyp/4.1.0/include/node/node_buffer.h:43:40: note: candidate function not viable: 2nd argument ('const char *') would lose const qualifier
NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                       ^
/Users/jeffrey.charles/.node-gyp/4.1.0/include/node/node_buffer.h:28:40: note: candidate function not viable: requires 2 arguments, but 3 were provided
NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate, size_t length);
                                       ^
/Users/jeffrey.charles/.node-gyp/4.1.0/include/node/node_buffer.h:36:40: note: candidate function not viable: requires 5 arguments, but 3 were provided
NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                       ^
In file included from ../src/debug.cc:2:
../node_modules/nan/nan.h:676:12: error: no viable conversion from 'v8::MaybeLocal<v8::Object>' to 'v8::Local<v8::Object>'
    return node::Buffer::New(v8::Isolate::GetCurrent(), size);
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/jeffrey.charles/.node-gyp/4.1.0/include/node/v8.h:210:7: note: candidate constructor (the implicit copy constructor) not viable: no known conversion from 'v8::MaybeLocal<v8::Object>' to
      'const v8::Local<v8::Object> &' for 1st argument
class Local {
      ^
/Users/jeffrey.charles/.node-gyp/4.1.0/include/node/v8.h:210:7: note: candidate constructor (the implicit move constructor) not viable: no known conversion from 'v8::MaybeLocal<v8::Object>' to
      'v8::Local<v8::Object> &&' for 1st argument
class Local {
      ^
/Users/jeffrey.charles/.node-gyp/4.1.0/include/node/v8.h:214:13: note: candidate template ignored: could not match 'Local' against 'MaybeLocal'
  V8_INLINE Local(Local<S> that)
            ^
/Users/jeffrey.charles/.node-gyp/4.1.0/include/node/v8.h:326:13: note: candidate template ignored: could not match 'S *' against 'v8::MaybeLocal<v8::Object>'
  V8_INLINE Local(S* that)
            ^
In file included from ../src/debug.cc:2:
../node_modules/nan/nan.h:683:26: error: no member named 'Use' in namespace 'node::Buffer'
    return node::Buffer::Use(v8::Isolate::GetCurrent(), data, size);
           ~~~~~~~~~~~~~~^
../src/debug.cc:194:25: warning: ISO C++11 does not allow conversion from string literal to 'char *' [-Wwritable-strings]
          result_type = "";
                        ^
In file included from ../src/debug.cc:2:
In file included from ../node_modules/nan/nan.h:24:
In file included from /Users/jeffrey.charles/.node-gyp/4.1.0/include/node/node.h:42:
/Users/jeffrey.charles/.node-gyp/4.1.0/include/node/v8.h:221:5: error: assigning to 'v8::Primitive *volatile' from incompatible type 'v8::Value *'
    TYPE_CHECK(T, S);
    ^~~~~~~~~~~~~~~~
/Users/jeffrey.charles/.node-gyp/4.1.0/include/node/v8.h:180:37: note: expanded from macro 'TYPE_CHECK'
    *(static_cast<T* volatile*>(0)) = static_cast<S*>(0);      \
                                    ^ ~~~~~~~~~~~~~~~~~~
../node_modules/nan/nan.h:414:12: note: in instantiation of function template specialization 'v8::Local<v8::Primitive>::Local<v8::Value>' requested here
    return NanEscapeScope(NanNew(v8::Undefined(v8::Isolate::GetCurrent())));
           ^
../node_modules/nan/nan.h:398:30: note: expanded from macro 'NanEscapeScope'
# define NanEscapeScope(val) scope.Escape(_NanEnsureLocal(val))
                             ^
In file included from ../src/debug.cc:2:
In file included from ../node_modules/nan/nan.h:24:
In file included from /Users/jeffrey.charles/.node-gyp/4.1.0/include/node/node.h:42:
/Users/jeffrey.charles/.node-gyp/4.1.0/include/node/v8.h:221:5: error: assigning to 'v8::Boolean *volatile' from incompatible type 'v8::Value *'
    TYPE_CHECK(T, S);
    ^~~~~~~~~~~~~~~~
/Users/jeffrey.charles/.node-gyp/4.1.0/include/node/v8.h:180:37: note: expanded from macro 'TYPE_CHECK'
    *(static_cast<T* volatile*>(0)) = static_cast<S*>(0);      \
                                    ^ ~~~~~~~~~~~~~~~~~~
../node_modules/nan/nan.h:424:12: note: in instantiation of function template specialization 'v8::Local<v8::Boolean>::Local<v8::Value>' requested here
    return NanEscapeScope(NanNew(v8::True(v8::Isolate::GetCurrent())));
           ^
../node_modules/nan/nan.h:398:30: note: expanded from macro 'NanEscapeScope'
# define NanEscapeScope(val) scope.Escape(_NanEnsureLocal(val))
                             ^
In file included from ../src/debug.cc:2:
In file included from ../node_modules/nan/nan.h:24:
In file included from /Users/jeffrey.charles/.node-gyp/4.1.0/include/node/node.h:42:
/Users/jeffrey.charles/.node-gyp/4.1.0/include/node/v8.h:221:5: error: assigning to 'v8::Function *volatile' from incompatible type 'v8::Value *'
    TYPE_CHECK(T, S);
    ^~~~~~~~~~~~~~~~
/Users/jeffrey.charles/.node-gyp/4.1.0/include/node/v8.h:180:37: note: expanded from macro 'TYPE_CHECK'
    *(static_cast<T* volatile*>(0)) = static_cast<S*>(0);      \
                                    ^ ~~~~~~~~~~~~~~~~~~
../node_modules/nan/nan.h:1514:12: note: in instantiation of function template specialization 'v8::Local<v8::Function>::Local<v8::Value>' requested here
    return NanEscapeScope(NanNew(handle)->Get(kCallbackIndex)
           ^
../node_modules/nan/nan.h:398:30: note: expanded from macro 'NanEscapeScope'
# define NanEscapeScope(val) scope.Escape(_NanEnsureLocal(val))
                             ^
In file included from ../src/debug.cc:2:
In file included from ../node_modules/nan/nan.h:24:
In file included from /Users/jeffrey.charles/.node-gyp/4.1.0/include/node/node.h:42:
/Users/jeffrey.charles/.node-gyp/4.1.0/include/node/v8.h:221:5: error: assigning to 'v8::Object *volatile' from incompatible type 'v8::Value *'
    TYPE_CHECK(T, S);
    ^~~~~~~~~~~~~~~~
/Users/jeffrey.charles/.node-gyp/4.1.0/include/node/v8.h:180:37: note: expanded from macro 'TYPE_CHECK'
    *(static_cast<T* volatile*>(0)) = static_cast<S*>(0);      \
                                    ^ ~~~~~~~~~~~~~~~~~~
../node_modules/nan/nan.h:1632:12: note: in instantiation of function template specialization 'v8::Local<v8::Object>::Local<v8::Value>' requested here
    return NanEscapeScope(handle->Get(NanNew(key)).As<v8::Object>());
           ^
../node_modules/nan/nan.h:398:30: note: expanded from macro 'NanEscapeScope'
# define NanEscapeScope(val) scope.Escape(_NanEnsureLocal(val))
                             ^
In file included from ../src/debug.cc:2:
In file included from ../node_modules/nan/nan.h:24:
In file included from /Users/jeffrey.charles/.node-gyp/4.1.0/include/node/node.h:42:
/Users/jeffrey.charles/.node-gyp/4.1.0/include/node/v8.h:221:5: error: assigning to 'v8::String *volatile' from incompatible type 'v8::Value *'
    TYPE_CHECK(T, S);
    ^~~~~~~~~~~~~~~~
/Users/jeffrey.charles/.node-gyp/4.1.0/include/node/v8.h:180:37: note: expanded from macro 'TYPE_CHECK'
    *(static_cast<T* volatile*>(0)) = static_cast<S*>(0);      \
                                    ^ ~~~~~~~~~~~~~~~~~~
../src/debug.cc:168:18: note: in instantiation of function template specialization 'v8::Local<v8::String>::Local<v8::Value>' requested here
          return NanEscapeScope(value->ToString());
                 ^
../node_modules/nan/nan.h:398:30: note: expanded from macro 'NanEscapeScope'
# define NanEscapeScope(val) scope.Escape(_NanEnsureLocal(val))
                             ^
1 warning and 10 errors generated.
make: *** [Release/obj.target/debug/src/debug.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/Cellar/nvm/0.26.1/versions/node/v4.1.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 14.5.0
gyp ERR! command "/usr/local/Cellar/nvm/0.26.1/versions/node/v4.1.0/bin/node" "/usr/local/Cellar/nvm/0.26.1/versions/node/v4.1.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/Users/jeffrey.charles/projects/iot-launch/node_modules/grunt-node-inspector/node_modules/node-inspector/node_modules/v8-debug/build/debug/v0.4.6/node-v46-darwin-x64/debug.node" "--module_name=debug" "--module_path=/Users/jeffrey.charles/projects/iot-launch/node_modules/grunt-node-inspector/node_modules/node-inspector/node_modules/v8-debug/build/debug/v0.4.6/node-v46-darwin-x64"
gyp ERR! cwd /Users/jeffrey.charles/projects/iot-launch/node_modules/grunt-node-inspector/node_modules/node-inspector/node_modules/v8-debug
gyp ERR! node -v v4.1.0
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/Cellar/nvm/0.26.1/versions/node/v4.1.0/bin/node /usr/local/Cellar/nvm/0.26.1/versions/node/v4.1.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/jeffrey.charles/projects/iot-launch/node_modules/grunt-node-inspector/node_modules/node-inspector/node_modules/v8-debug/build/debug/v0.4.6/node-v46-darwin-x64/debug.node --module_name=debug --module_path=/Users/jeffrey.charles/projects/iot-launch/node_modules/grunt-node-inspector/node_modules/node-inspector/node_modules/v8-debug/build/debug/v0.4.6/node-v46-darwin-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/jeffrey.charles/projects/iot-launch/node_modules/grunt-node-inspector/node_modules/node-inspector/node_modules/v8-debug/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:87:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:817:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
node-pre-gyp ERR! System Darwin 14.5.0
node-pre-gyp ERR! command "/usr/local/Cellar/nvm/0.26.1/versions/node/v4.1.0/bin/node" "/Users/jeffrey.charles/projects/iot-launch/node_modules/grunt-node-inspector/node_modules/node-inspector/node_modules/v8-debug/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/jeffrey.charles/projects/iot-launch/node_modules/grunt-node-inspector/node_modules/node-inspector/node_modules/v8-debug
node-pre-gyp ERR! node -v v4.1.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.11
node-pre-gyp ERR! not ok 
Failed to execute '/usr/local/Cellar/nvm/0.26.1/versions/node/v4.1.0/bin/node /usr/local/Cellar/nvm/0.26.1/versions/node/v4.1.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/jeffrey.charles/projects/iot-launch/node_modules/grunt-node-inspector/node_modules/node-inspector/node_modules/v8-debug/build/debug/v0.4.6/node-v46-darwin-x64/debug.node --module_name=debug --module_path=/Users/jeffrey.charles/projects/iot-launch/node_modules/grunt-node-inspector/node_modules/node-inspector/node_modules/v8-debug/build/debug/v0.4.6/node-v46-darwin-x64' (1)
npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/Cellar/nvm/0.26.1/versions/node/v4.1.0/bin/node" "/usr/local/opt/nvm/versions/node/v4.1.0/bin/npm" "install"
npm ERR! node v4.1.0
npm ERR! npm  v2.14.3
npm ERR! code ELIFECYCLE

npm ERR! v8-debug@0.4.6 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the v8-debug@0.4.6 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! This is most likely a problem with the v8-debug package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get their info via:
npm ERR!     npm owner ls v8-debug
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/jeffrey.charles/projects/iot-launch/npm-debug.log
```

I suspect this is due to https://github.com/ChrisWren/grunt-node-inspector/issues/32 but I thought I'd call it out here since there is nothing in the README to indicate incompatibility with Node v4.

**Comment by vhuerta** [comment]
+1
